---
name: CI / Format
run-name: CI | Format

concurrency:
  group: ${{ github.workflow_ref }}-${{ github.ref }}
  cancel-in-progress: true

"on":
  pull_request:
    branches:
      - main

jobs:
  format:
    name: Format
    runs-on: simplepark-runners

    steps:
      - uses: actions/checkout@v4

      - name: Lint Markdown
        uses: DavidAnson/markdownlint-cli2-action@v22
        with:
          globs: |
            **/*.md
            !**/node_modules/**
